// UI strings: [English, Tamil]. Wording rule from the plan: say "stake",
// "entry" or "challenge" for coins in rooms, never "bet" or "wager"
// (Tamil: நுழைவுத் தொகை, never பந்தயம்).

export const strings = {
  'app.name': ['Group 4 Quiz Battle', 'குரூப் 4 வினாடி வினா'],
  'app.tagline': ['Practise TNPSC Group 4 like a game', 'TNPSC குரூப் 4 — விளையாட்டாகப் படிப்போம்'],

  'common.back': ['Back', 'பின்செல்'],
  'common.close': ['Close', 'மூடு'],
  'common.cancel': ['Cancel', 'ரத்து'],
  'common.save': ['Save', 'சேமி'],
  'common.continue': ['Continue', 'தொடர்க'],
  'common.retry': ['Try again', 'மீண்டும் முயல்க'],
  'common.loading': ['Loading…', 'ஏற்றுகிறது…'],
  'common.coins': ['coins', 'நாணயங்கள்'],
  'common.level': ['Level {n}', 'நிலை {n}'],
  'common.copy': ['Copy', 'நகலெடு'],
  'common.copied': ['Copied', 'நகலெடுக்கப்பட்டது'],
  'common.share': ['Share', 'பகிர்'],
  'common.done': ['Done', 'முடிந்தது'],
  'common.offline': ['You are offline', 'இணைய இணைப்பு இல்லை'],
  'common.demo': ['Demo mode: solo practice with sample questions. Connect Supabase to play rooms with friends.', 'டெமோ முறை: மாதிரி வினாக்களுடன் தனிப் பயிற்சி. நண்பர்களுடன் விளையாட Supabase-ஐ இணைக்கவும்.'],
  'common.needsServer': ['This needs the online server (demo mode).', 'இதற்கு ஆன்லைன் சேவையகம் தேவை (டெமோ முறை).'],
  'common.seeAll': ['See all', 'அனைத்தும்'],

  'lang.ta': ['தமிழ்', 'தமிழ்'],
  'lang.en': ['English', 'English'],

  'nav.home': ['Home', 'முகப்பு'],
  'nav.play': ['Solo', 'பயிற்சி'],
  'nav.friends': ['Friends', 'நண்பர்கள்'],
  'nav.ranks': ['Ranks', 'தரவரிசை'],
  'nav.profile': ['Me', 'நான்'],

  'welcome.pickLang': ['Choose your language', 'மொழியைத் தேர்ந்தெடுக்கவும்'],
  'welcome.email': ['Email me a sign-in code', 'உள்நுழைவுக் குறியீட்டை மின்னஞ்சலில் அனுப்பு'],
  'welcome.code': ['6-digit code from the email', 'மின்னஞ்சலில் வந்த 6 இலக்கக் குறியீடு'],
  'welcome.verify': ['Sign in', 'உள்நுழை'],
  'welcome.badCode': ['That code is wrong or expired. Request a new one.', 'குறியீடு தவறு அல்லது காலாவதியானது. புதியதைக் கோரவும்.'],
  'welcome.changeEmail': ['Use a different email', 'வேறு மின்னஞ்சல்'],
  'welcome.linkSent': ['We emailed {email}. Type the 6-digit code below, or tap the link in the email on this phone.', '{email} முகவரிக்கு மின்னஞ்சல் அனுப்பியுள்ளோம். கீழே 6 இலக்கக் குறியீட்டை உள்ளிடவும், அல்லது இதே தொலைபேசியில் இணைப்பைத் தட்டவும்.'],
  'welcome.p1': ['Earn coins in 5-minute solo sets', '5 நிமிடத் தனிப் பயிற்சியில் நாணயங்கள் சேர்க்கவும்'],
  'welcome.p2': ['Challenge friends in live rooms', 'நண்பர்களுடன் நேரடிப் போட்டி'],
  'welcome.p3': ['Real exam pattern, Tamil and English', 'உண்மையான தேர்வு முறை, தமிழ் & ஆங்கிலம்'],
  'welcome.free': ['Free to play. Coins are game points only: never bought, sold or cashed out.', 'இலவசம். நாணயங்கள் விளையாட்டுப் புள்ளிகள் மட்டுமே: வாங்கவோ விற்கவோ பணமாக்கவோ முடியாது.'],
  'welcome.legal': ['By continuing you accept the Terms and the Privacy Policy.', 'தொடர்வதன் மூலம் விதிமுறைகளையும் தனியுரிமைக் கொள்கையையும் ஏற்கிறீர்கள்.'],

  'onb.title': ['Set up your profile', 'உங்கள் சுயவிவரம்'],
  'onb.name': ['Your name', 'உங்கள் பெயர்'],
  'onb.username': ['Username (friends find you by this)', 'பயனர் பெயர் (நண்பர்கள் இதைக் கொண்டு தேடுவர்)'],
  'onb.usernameHint': ['3–20 characters: a–z, 0–9 and _', '3–20 எழுத்துகள்: a–z, 0–9, _'],
  'onb.district': ['District', 'மாவட்டம்'],
  'onb.pickDistrict': ['Choose your district', 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்'],
  'onb.examYear': ['Target exam year', 'இலக்குத் தேர்வு ஆண்டு'],
  'onb.referrer': ['Invited by (username, optional)', 'அழைத்தவர் (பயனர் பெயர், விருப்பம்)'],
  'onb.adult': ['I am 18 or older', 'எனக்கு 18 வயது அல்லது அதற்கு மேல்'],
  'onb.consent': ['I agree to the Terms and Privacy Policy. Only my email, name, district and exam year are kept.', 'விதிமுறைகளையும் தனியுரிமைக் கொள்கையையும் ஏற்கிறேன். என் மின்னஞ்சல், பெயர், மாவட்டம், தேர்வு ஆண்டு மட்டுமே சேமிக்கப்படும்.'],
  'onb.submit': ['Next: 3-question warm-up', 'அடுத்து: 3 வினா பயிற்சி'],

  'demo.title': ['Warm-up: 3 questions', 'பயிற்சி: 3 வினாக்கள்'],
  'demo.bonusTitle': ['500 coins are yours!', '500 நாணயங்கள் உங்களுக்கு!'],
  'demo.bonusBody': ['Use them as entry in a room with friends, or grow them in solo practice.', 'நண்பர்களுடன் அறைப் போட்டியில் நுழைவுத் தொகையாகப் பயன்படுத்துங்கள், அல்லது தனிப் பயிற்சியில் பெருக்குங்கள்.'],
  'demo.bonusLimited': ['This phone has already claimed starter coins, so this account starts at 0. Earn coins in solo practice.', 'இந்தத் தொலைபேசியில் ஏற்கெனவே தொடக்க நாணயங்கள் பெறப்பட்டுள்ளன. தனிப் பயிற்சியில் நாணயங்கள் சேர்க்கவும்.'],
  'demo.invite': ['Invite a friend to a room', 'நண்பரை அறைக்கு அழை'],
  'demo.solo': ['Play solo', 'தனியாக விளையாடு'],

  'home.hello': ['Vanakkam, {name}!', 'வணக்கம், {name}!'],
  'home.examIn': ['{days} days to the exam', 'தேர்வுக்கு {days} நாட்கள்'],
  'home.examToday': ['Exam day: all the best!', 'இன்று தேர்வு: வாழ்த்துகள்!'],
  'home.plan': ['Today: 2 solo sets + daily challenge', 'இன்று: 2 தனிப் பயிற்சி + இன்றைய சவால்'],
  'home.playSolo': ['Play Solo', 'தனிப் பயிற்சி'],
  'home.playSoloSub': ['10 questions · earn coins', '10 வினாக்கள் · நாணயங்கள் சேர்'],
  'home.createRoom': ['Create Room', 'அறை உருவாக்கு'],
  'home.joinRoom': ['Join Room', 'அறையில் சேர்'],
  'home.daily': ['Daily Challenge', 'இன்றைய சவால்'],
  'home.dailyBody': ['15 questions · same set for everyone · +100 to +300 coins', '15 வினாக்கள் · அனைவருக்கும் ஒரே தொகுப்பு · +100 முதல் +300 நாணயங்கள்'],
  'home.dailyDone': ['Done today · score {score}', 'இன்று முடிந்தது · மதிப்பெண் {score}'],
  'home.dailyPlayers': ['{n} played today', 'இன்று {n} பேர் விளையாடினர்'],
  'home.board': ['Leaderboard', 'தரவரிசை'],
  'home.streak': ['{n}-day streak', '{n} நாள் தொடர்'],
  'home.streakTodo': ['Play one solo set today to keep it', 'தக்கவைக்க இன்று ஒரு பயிற்சி செய்க'],
  'home.streakDone': ['Streak kept for today', 'இன்றைய தொடர் உறுதி'],
  'home.revision': ['Revision deck', 'மீள்பார்வைத் தொகுப்பு'],
  'home.revisionDue': ['{n} questions due', '{n} வினாக்கள் காத்திருக்கின்றன'],
  'home.mock': ['Weekly Mock Test', 'வாராந்திர மாதிரித் தேர்வு'],
  'home.mockBody': ['200 questions, real exam pattern · pausable · +500 coins', '200 வினாக்கள், தேர்வு முறை · இடைநிறுத்தலாம் · +500 நாணயங்கள்'],
  'home.mockResume': ['Resume your mock', 'மாதிரித் தேர்வைத் தொடர்க'],
  'home.mockDone': ['Done this week', 'இந்த வாரம் முடிந்தது'],
  'home.friendsOnline': ['Friends online', 'இணையத்தில் நண்பர்கள்'],
  'home.noFriendsOnline': ['No friends online right now. Invite your study group!', 'இப்போது நண்பர்கள் இல்லை. உங்கள் படிப்புக் குழுவை அழையுங்கள்!'],
  'home.refill': ['Low on coins? Free top-up to 200', 'நாணயங்கள் குறைவா? இலவசமாக 200 வரை'],
  'home.refillClaim': ['Claim', 'பெறுக'],
  'home.resumeRoom': ['Back to your room {code}', 'உங்கள் அறை {code}-க்குத் திரும்பு'],
  'home.resumeMatch': ['Match in progress: rejoin', 'போட்டி நடக்கிறது: மீண்டும் சேர்'],
  'home.weekXp': ['{xp} XP this week', 'இந்த வாரம் {xp} XP'],
  'home.soloCoins': ['Solo coins today {n}/{cap}', 'இன்றைய பயிற்சி நாணயங்கள் {n}/{cap}'],
  'home.synced': ['Offline practice synced: +{coins} coins', 'ஆஃப்லைன் பயிற்சி ஒத்திசைந்தது: +{coins} நாணயங்கள்'],
  'home.requests': ['{n} friend requests', '{n} நண்பர் கோரிக்கைகள்'],

  'solo.title': ['Solo Practice', 'தனிப் பயிற்சி'],
  'solo.subject': ['Subject', 'பாடம்'],
  'solo.mixed': ['Mixed (exam pattern)', 'கலவை (தேர்வு முறை)'],
  'solo.level': ['Difficulty', 'கடினம்'],
  'solo.auto': ['Auto', 'தானியங்கி'],
  'solo.easy': ['Easy', 'எளிது'],
  'solo.medium': ['Medium', 'நடுத்தரம்'],
  'solo.hard': ['Hard', 'கடினம்'],
  'solo.start': ['Start 10 questions', '10 வினாக்களைத் தொடங்கு'],
  'solo.rules': ['20 s per question · +5 coins per correct · +20 for finishing (max 300 a day)', 'ஒரு வினாவுக்கு 20 வி · சரிக்கு +5 · முடித்தால் +20 (நாளொன்றுக்கு அதிகபட்சம் 300)'],
  'solo.revisionStart': ['Revise your deck', 'மீள்பார்வை செய்'],
  'solo.revisionBody': ['Questions you got wrong come back here, spaced out until you master them.', 'தவறிய வினாக்கள் இங்கே மீண்டும் வரும் — தேர்ச்சி பெறும் வரை இடைவெளி விட்டு.'],
  'solo.offline': ['Offline practice', 'ஆஃப்லைன் பயிற்சி'],
  'solo.offlineBody': ['Keep questions on this phone to practise without internet. Coins are added when you are back online (max 100 per session).', 'இணையம் இல்லாமல் பயிற்சி செய்ய வினாக்களை இத்தொலைபேசியில் சேமிக்கவும். இணையம் வந்ததும் நாணயங்கள் சேரும் (ஒரு முறைக்கு அதிகபட்சம் 100).'],
  'solo.offlineDownload': ['Download questions', 'வினாக்களைப் பதிவிறக்கு'],
  'solo.offlineReady': ['{n} questions ready offline', '{n} வினாக்கள் ஆஃப்லைனில் தயார்'],
  'solo.offlineStart': ['Practise offline', 'ஆஃப்லைனில் பயிற்சி'],
  'solo.subtopic': ['Topic: {name}', 'தலைப்பு: {name}'],

  'play.question': ['Question {i} of {n}', 'வினா {i} / {n}'],
  'play.timeUp': ['Time up!', 'நேரம் முடிந்தது!'],
  'play.correct': ['Correct!', 'சரி!'],
  'play.wrong': ['Not quite', 'தவறு'],
  'play.points': ['+{n} points', '+{n} புள்ளிகள்'],
  'play.streak': ['{n} in a row', 'தொடர்ந்து {n}'],
  'play.next': ['Next', 'அடுத்து'],
  'play.finish': ['See result', 'முடிவைப் பார்'],
  'play.explanation': ['Why', 'விளக்கம்'],
  'play.addRevision': ['Add to revision deck', 'மீள்பார்வையில் சேர்'],
  'play.addedRevision': ['In your revision deck', 'மீள்பார்வையில் உள்ளது'],
  'play.report': ['Report question', 'வினாவைப் புகாரளி'],
  'play.reported': ['Thanks! We check reports within 48 hours.', 'நன்றி! 48 மணிநேரத்துக்குள் சரிபார்ப்போம்.'],
  'play.quit': ['Quit', 'வெளியேறு'],
  'play.quitConfirm': ['Leave this set? You will lose the coins for it.', 'இந்தப் பயிற்சியை விட்டு வெளியேறவா? இதற்கான நாணயங்கள் கிடைக்காது.'],
  'play.ref': ['Book: {ref}', 'நூல்: {ref}'],
  'play.answerIs': ['Answer: {a}', 'விடை: {a}'],

  'report.title': ['What is wrong with this question?', 'இந்த வினாவில் என்ன தவறு?'],
  'report.wrong_answer': ['Wrong answer', 'தவறான விடை'],
  'report.typo': ['Typo or unclear', 'எழுத்துப்பிழை / தெளிவில்லை'],
  'report.translation': ['Bad translation', 'தவறான மொழிபெயர்ப்பு'],
  'report.outdated': ['Out of date', 'பழைய தகவல்'],
  'report.abuse': ['Abusive', 'அவதூறு'],
  'report.spam': ['Spam or scam', 'ஸ்பேம் / மோசடி'],
  'report.other': ['Other', 'மற்றவை'],
  'report.details': ['Details (optional)', 'விவரம் (விருப்பம்)'],
  'report.send': ['Send report', 'புகார் அனுப்பு'],

  'result.title': ['Set complete', 'பயிற்சி முடிந்தது'],
  'result.correct': ['{c} of {n} correct', '{n}-ல் {c} சரி'],
  'result.score': ['{n} points', '{n} புள்ளிகள்'],
  'result.coins': ['+{n} coins', '+{n} நாணயங்கள்'],
  'result.capHit': ['Daily solo coin limit (300) reached. XP still counts!', 'இன்றைய பயிற்சி நாணய வரம்பு (300) எட்டியது. XP தொடரும்!'],
  'result.xp': ['+{n} XP', '+{n} XP'],
  'result.levelUp': ['Level up! You are now {title} (+{coins} coins)', 'நிலை உயர்வு! இப்போது நீங்கள் {title} (+{coins} நாணயங்கள்)'],
  'result.streak': ['Day {n} of your streak: +{coins} coins', 'தொடரின் {n}-ம் நாள்: +{coins} நாணயங்கள்'],
  'result.shieldUsed': ['A streak shield saved your streak!', 'கேடயம் உங்கள் தொடரைக் காத்தது!'],
  'result.weak': ['Weak topics to practise', 'பயிற்சி தேவைப்படும் தலைப்புகள்'],
  'result.practise': ['Practise', 'பயிற்சி'],
  'result.playAgain': ['Play again', 'மீண்டும் விளையாடு'],
  'result.dailyRank': ['You are #{rank} today so far', 'இன்று இதுவரை நீங்கள் #{rank}'],
  'result.dailyReward': ['Rank rewards (+100 to +300 coins) arrive after midnight.', 'தரவரிசைப் பரிசு (+100 முதல் +300) நள்ளிரவுக்குப் பின் சேரும்.'],
  'result.pendingSync': ['Coins will be added when you are back online.', 'இணையம் வந்ததும் நாணயங்கள் சேர்க்கப்படும்.'],
  'result.badge': ['Badge earned: {name}', 'பதக்கம் பெற்றீர்கள்: {name}'],

  'mock.title': ['Mock Test', 'மாதிரித் தேர்வு'],
  'mock.intro': ['200 questions in the real pattern: Part A Tamil (100), Part B General Studies and Aptitude (100). 3 hours. Pause any time: answers are saved.', 'உண்மையான முறையில் 200 வினாக்கள்: பகுதி அ தமிழ் (100), பகுதி ஆ பொது அறிவு & திறனறிவு (100). 3 மணிநேரம். எப்போது வேண்டுமானாலும் இடைநிறுத்தலாம்: விடைகள் சேமிக்கப்படும்.'],
  'mock.start': ['Start mock test', 'மாதிரித் தேர்வைத் தொடங்கு'],
  'mock.timeLeft': ['Time left', 'மீதமுள்ள நேரம்'],
  'mock.prev': ['Previous', 'முந்தையது'],
  'mock.next': ['Next', 'அடுத்து'],
  'mock.palette': ['All questions', 'அனைத்து வினாக்கள்'],
  'mock.submit': ['Submit test', 'தேர்வைச் சமர்ப்பி'],
  'mock.submitConfirm': ['Submit now? {left} questions are unanswered.', 'இப்போது சமர்ப்பிக்கவா? {left} வினாக்களுக்கு விடையளிக்கவில்லை.'],
  'mock.pause': ['Pause and exit', 'இடைநிறுத்தி வெளியேறு'],
  'mock.marks': ['{marks} / 300 marks', '{marks} / 300 மதிப்பெண்கள்'],
  'mock.byUnit': ['By unit', 'பாடவாரியாக'],
  'mock.reward': ['+500 coins for this week’s mock', 'இந்த வார மாதிரித் தேர்வுக்கு +500 நாணயங்கள்'],
  'mock.noReward': ['Answer at least 80% of questions to earn the weekly +500.', 'வாராந்திர +500 பெற குறைந்தது 80% வினாக்களுக்கு விடையளிக்கவும்.'],
  'mock.answered': ['{a} of {n} answered', '{n}-ல் {a} விடையளிக்கப்பட்டது'],
  'mock.clear': ['Clear answer', 'விடையை நீக்கு'],

  'daily.title': ['Daily Challenge', 'இன்றைய சவால்'],
  'daily.start': ['Start today’s challenge', 'இன்றைய சவாலைத் தொடங்கு'],
  'daily.rules': ['15 questions · 20 s each · one attempt. Top 10% get 300 coins, top 40% get 200, everyone who finishes gets 100.', '15 வினாக்கள் · தலா 20 வி · ஒரே முயற்சி. முதல் 10%-க்கு 300, முதல் 40%-க்கு 200, முடித்த அனைவருக்கும் 100 நாணயங்கள்.'],
  'daily.board': ['Today’s leaderboard', 'இன்றைய தரவரிசை'],
  'daily.empty': ['No one has finished yet. Be the first!', 'இன்னும் யாரும் முடிக்கவில்லை. முதலில் நீங்கள்!'],

  'room.create': ['Create a room', 'அறை உருவாக்கு'],
  'room.size': ['Players', 'வீரர்கள்'],
  'room.subject': ['Subject', 'பாடம்'],
  'room.count': ['Questions', 'வினாக்கள்'],
  'room.language': ['Question language', 'வினா மொழி'],
  'room.stake': ['Entry coins (each player)', 'நுழைவுத் தொகை (ஒவ்வொருவரும்)'],
  'room.friendly': ['Friendly', 'நட்பு'],
  'room.unlockAt': ['Level {n}', 'நிலை {n}'],
  'room.powerups': ['Power-ups (50:50, +10 s)', 'உதவிகள் (50:50, +10 வி)'],
  'room.difficulty': ['Difficulty', 'கடினம்'],
  'room.split2': ['Winner gets 90% of the pot', 'வெற்றியாளருக்கு மொத்தத்தில் 90%'],
  'room.split3': ['1st gets 70% · 2nd gets 20%', '1-ம் இடம் 70% · 2-ம் இடம் 20%'],
  'room.split4': ['1st gets 60% · 2nd gets 30%', '1-ம் இடம் 60% · 2-ம் இடம் 30%'],
  'room.houseCut': ['10% of every pot leaves the game. Ties on points go to the faster player.', 'ஒவ்வொரு மொத்தத்திலும் 10% விளையாட்டிலிருந்து நீக்கப்படும். சம புள்ளிகளில் வேகமானவர் வெல்வார்.'],
  'room.createBtn': ['Create room', 'அறையை உருவாக்கு'],
  'room.join': ['Join a room', 'அறையில் சேர்'],
  'room.codeLabel': ['Room code (6 characters)', 'அறைக் குறியீடு (6 எழுத்துகள்)'],
  'room.joinBtn': ['Join', 'சேர்'],
  'room.code': ['Room code', 'அறைக் குறியீடு'],
  'room.shareWa': ['Share on WhatsApp', 'WhatsApp-ல் பகிர்'],
  'room.shareText': ['Join my Group 4 quiz room! Code {code} · entry {stake} coins', 'என் குரூப் 4 வினாடி வினா அறையில் சேருங்கள்! குறியீடு {code} · நுழைவு {stake} நாணயங்கள்'],
  'room.emptySeat': ['Waiting…', 'காத்திருக்கிறது…'],
  'room.host': ['Host', 'நடத்துநர்'],
  'room.ready': ['Ready', 'தயார்'],
  'room.notReady': ['Not ready', 'தயாரில்லை'],
  'room.imReady': ['I’m ready', 'நான் தயார்'],
  'room.cancelReady': ['Not ready yet', 'இன்னும் தயாரில்லை'],
  'room.start': ['Start match', 'போட்டியைத் தொடங்கு'],
  'room.startHint': ['Needs 2+ players, all ready', '2+ வீரர்கள், அனைவரும் தயார்'],
  'room.leave': ['Leave room', 'அறையை விட்டு வெளியேறு'],
  'room.cantAfford': ['Not enough coins', 'நாணயங்கள் போதாது'],
  'room.inviteFriends': ['Invite friends', 'நண்பர்களை அழை'],
  'room.invited': ['Invite sent', 'அழைப்பு அனுப்பப்பட்டது'],
  'room.escrow': ['Entry coins are locked when the match starts and settled when it ends. A failed match is fully refunded.', 'போட்டி தொடங்கும்போது நுழைவுத் தொகை பூட்டப்பட்டு, முடிவில் கணக்கிடப்படும். தோல்வியடைந்த போட்டிக்கு முழுத் தொகையும் திருப்பித் தரப்படும்.'],
  'room.away': ['away', 'இல்லை'],
  'room.pot': ['Pot: {pot} coins', 'மொத்தம்: {pot} நாணயங்கள்'],
  'room.joining': ['Joining room…', 'அறையில் சேர்கிறது…'],
  'room.sizeLocked': ['4-player rooms unlock at level {n}', '4 வீரர் அறைகள் நிலை {n}-ல் திறக்கும்'],

  'match.starting': ['Get ready…', 'தயாராகுங்கள்…'],
  'match.waiting': ['Waiting for others…', 'மற்றவர்களுக்காகக் காத்திருக்கிறோம்…'],
  'match.locked': ['Answer locked', 'விடை பூட்டப்பட்டது'],
  'match.you': ['You: +{n}', 'நீங்கள்: +{n}'],
  'match.noAnswer': ['No answer', 'விடையில்லை'],
  'match.reconnecting': ['Reconnecting…', 'மீண்டும் இணைகிறது…'],
  'match.over': ['Match over', 'போட்டி முடிந்தது'],
  'match.extra': ['+10 s used', '+10 வி பயன்படுத்தப்பட்டது'],

  'mres.title': ['Results', 'முடிவுகள்'],
  'mres.won': ['You won {n} coins!', 'நீங்கள் {n} நாணயங்கள் வென்றீர்கள்!'],
  'mres.lost': ['Good fight! Practise and come back stronger.', 'நல்ல போட்டி! பயிற்சி செய்து வலுவாகத் திரும்புங்கள்.'],
  'mres.refunded': ['Match cancelled: entry coins refunded', 'போட்டி ரத்து: நுழைவுத் தொகை திருப்பித் தரப்பட்டது'],
  'mres.rematch': ['Rematch', 'மீண்டும் போட்டி'],
  'mres.settling': ['Settling the pot…', 'கணக்கிடப்படுகிறது…'],
  'mres.pts': ['{n} pts', '{n} புள்ளி'],

  'chat.placeholder': ['Message (max 200)', 'செய்தி (அதிகபட்சம் 200)'],
  'chat.send': ['Send', 'அனுப்பு'],
  'chat.typing': ['typing…', 'தட்டச்சு செய்கிறார்…'],
  'chat.seen': ['Seen', 'பார்த்தார்'],
  'chat.emojiOnly': ['Emoji only during a question', 'வினாவின்போது எமோஜி மட்டும்'],
  'chat.invite': ['Room invite · {stake} coins · {size} players', 'அறை அழைப்பு · {stake} நாணயங்கள் · {size} வீரர்கள்'],
  'chat.join': ['Join', 'சேர்'],
  'chat.mute': ['Hide this player', 'இவரை மறை'],
  'chat.unmute': ['Show this player', 'இவரைக் காட்டு'],
  'chat.block': ['Block', 'தடு'],
  'chat.report': ['Report', 'புகாரளி'],
  'chat.empty': ['Say vanakkam 👋', 'வணக்கம் சொல்லுங்கள் 👋'],
  'chat.reported': ['Reported. Thanks for keeping chat safe.', 'புகாரளிக்கப்பட்டது. நன்றி.'],

  'phrase.gg': ['Well played!', 'நல்லா விளையாடினே!'],
  'phrase.rematch': ['Rematch?', 'மறுபடியும் ஆடலாமா?'],
  'phrase.easy': ['Too easy 😎', 'ரொம்ப ஈஸி 😎'],
  'phrase.luck': ['All the best!', 'வாழ்த்துகள்!'],
  'phrase.wow': ['Awesome!', 'அருமை!'],
  'phrase.tough': ['That was tough!', 'கஷ்டமா இருந்தது!'],

  'friends.title': ['Friends', 'நண்பர்கள்'],
  'friends.tabFriends': ['Friends', 'நண்பர்கள்'],
  'friends.tabRequests': ['Requests', 'கோரிக்கைகள்'],
  'friends.tabFind': ['Find', 'தேடு'],
  'friends.search': ['Search by username or name', 'பயனர் பெயர் அல்லது பெயரால் தேடு'],
  'friends.add': ['Add', 'சேர்'],
  'friends.requested': ['Requested', 'கோரப்பட்டது'],
  'friends.isFriend': ['Friends', 'நண்பர்'],
  'friends.accept': ['Accept', 'ஏற்கவும்'],
  'friends.decline': ['Decline', 'நிராகரி'],
  'friends.remove': ['Remove friend', 'நண்பர் நீக்கு'],
  'friends.none': ['No friends yet. Find your study group by username, or invite them on WhatsApp.', 'இன்னும் நண்பர்கள் இல்லை. பயனர் பெயரால் தேடுங்கள் அல்லது WhatsApp-ல் அழையுங்கள்.'],
  'friends.noRequests': ['No pending requests', 'நிலுவைக் கோரிக்கைகள் இல்லை'],
  'friends.online': ['Online', 'இணையத்தில்'],
  'friends.blocked': ['Blocked', 'தடுக்கப்பட்டவர்கள்'],
  'friends.unblock': ['Unblock', 'தடை நீக்கு'],
  'friends.inviteWa': ['Invite on WhatsApp', 'WhatsApp-ல் அழை'],
  'friends.inviteText': ['Practise TNPSC Group 4 with me! My username: {username}', 'என்னுடன் TNPSC குரூப் 4 பயிற்சி செய்யுங்கள்! என் பயனர் பெயர்: {username}'],
  'friends.incoming': ['Wants to be friends', 'நண்பராக விரும்புகிறார்'],
  'friends.outgoing': ['Sent requests', 'அனுப்பிய கோரிக்கைகள்'],
  'friends.chat': ['Chat', 'அரட்டை'],
  'friends.h2h': ['Head to head: {w}–{l}', 'நேருக்கு நேர்: {w}–{l}'],

  'lb.title': ['Leaderboards', 'தரவரிசைகள்'],
  'lb.friends': ['Friends', 'நண்பர்கள்'],
  'lb.district': ['District', 'மாவட்டம்'],
  'lb.state': ['State', 'மாநிலம்'],
  'lb.daily': ['Today', 'இன்று'],
  'lb.overall': ['All subjects (XP)', 'அனைத்துப் பாடங்கள் (XP)'],
  'lb.week': ['This week (Mon–Sun)', 'இந்த வாரம் (திங்கள்–ஞாயிறு)'],
  'lb.you': ['You', 'நீங்கள்'],
  'lb.empty': ['Nobody here yet this week. Play to get on the board!', 'இந்த வாரம் இன்னும் யாரும் இல்லை. விளையாடிப் பட்டியலில் இடம்பெறுங்கள்!'],
  'lb.correct': ['{n} correct', '{n} சரி'],

  'profile.badges': ['Badges', 'பதக்கங்கள்'],
  'profile.accuracy': ['Accuracy by unit', 'பாடவாரி துல்லியம்'],
  'profile.coinHistory': ['Coin history', 'நாணய வரலாறு'],
  'profile.matches': ['{m} rooms · {w} wins', '{m} அறைகள் · {w} வெற்றிகள்'],
  'profile.soloSets': ['{n} solo sets', '{n} தனிப் பயிற்சிகள்'],
  'profile.shields': ['Streak shields: {n}', 'தொடர்க் கேடயங்கள்: {n}'],
  'profile.buyShield': ['Buy shield · 150', 'கேடயம் வாங்கு · 150'],
  'profile.settings': ['Settings', 'அமைப்புகள்'],
  'profile.language': ['Language', 'மொழி'],
  'profile.sound': ['Sound effects', 'ஒலி விளைவுகள்'],
  'profile.haptics': ['Vibration', 'அதிர்வு'],
  'profile.graphics': ['Graphics', 'வரைகலை'],
  'profile.batterySaver': ['Battery saver (no 3D)', 'பேட்டரி சேமிப்பு (3D இல்லை)'],
  'profile.strangers': ['Allow chat from non-friends', 'நண்பரல்லாதோர் அரட்டையை அனுமதி'],
  'profile.install': ['Install app', 'செயலியை நிறுவு'],
  'profile.signOut': ['Sign out', 'வெளியேறு'],
  'profile.delete': ['Delete my account', 'என் கணக்கை நீக்கு'],
  'profile.deleteConfirm': ['This permanently deletes your account, coins and history. Type DELETE to confirm.', 'இது உங்கள் கணக்கு, நாணயங்கள், வரலாறு அனைத்தையும் நிரந்தரமாக நீக்கும். உறுதிப்படுத்த DELETE என்று தட்டச்சு செய்யவும்.'],
  'profile.admin': ['Admin panel', 'நிர்வாகப் பகுதி'],
  'profile.terms': ['Terms of use', 'பயன்பாட்டு விதிமுறைகள்'],
  'profile.privacy': ['Privacy policy', 'தனியுரிமைக் கொள்கை'],
  'profile.edit': ['Edit profile', 'சுயவிவரத்தைத் திருத்து'],
  'profile.avatar': ['Avatar', 'அவதாரம்'],
  'profile.weak': ['Weakest topics', 'பலவீனமான தலைப்புகள்'],
  'profile.revision': ['{n} questions in your revision deck', 'மீள்பார்வையில் {n} வினாக்கள்'],
  'profile.coinsRule': ['Coins are free game points. They cannot be bought, sold, transferred or cashed out.', 'நாணயங்கள் இலவச விளையாட்டுப் புள்ளிகள். அவற்றை வாங்கவோ, விற்கவோ, மாற்றவோ, பணமாக்கவோ முடியாது.'],
  'profile.recentRooms': ['Recent rooms', 'சமீபத்திய அறைகள்'],
  'profile.nextLevel': ['{xp} XP to level {n}', 'நிலை {n}-க்கு {xp} XP'],

  'reason.signup_bonus': ['Starter coins', 'தொடக்க நாணயங்கள்'],
  'reason.solo': ['Solo practice', 'தனிப் பயிற்சி'],
  'reason.streak': ['Daily streak', 'தினசரித் தொடர்'],
  'reason.daily_rank': ['Daily challenge rank', 'இன்றைய சவால் தரம்'],
  'reason.mock': ['Weekly mock', 'வாராந்திர மாதிரித் தேர்வு'],
  'reason.achievement': ['Badge', 'பதக்கம்'],
  'reason.level_up': ['Level up', 'நிலை உயர்வு'],
  'reason.referral': ['Friend referral', 'நண்பர் பரிந்துரை'],
  'reason.refill': ['Free top-up', 'இலவச நிரப்பல்'],
  'reason.room_stake': ['Room entry', 'அறை நுழைவு'],
  'reason.room_win': ['Room winnings', 'அறை வெற்றி'],
  'reason.powerup': ['Power-up', 'உதவி'],
  'reason.shield': ['Streak shield', 'தொடர்க் கேடயம்'],
  'reason.report_reward': ['Report upheld', 'புகார் ஏற்கப்பட்டது'],

  'tier.high': ['High (3D)', 'உயர் (3D)'],
  'tier.medium': ['Medium (3D)', 'நடுத்தர (3D)'],
  'tier.low': ['Light (2D)', 'இலகு (2D)'],
  'tier.reduced': ['Reduced motion', 'குறைந்த அசைவு'],

  'install.title': ['Install the app', 'செயலியை நிறுவுக'],
  'install.body': ['Add Group 4 Quiz to your home screen: it opens full-screen and solo practice works offline.', 'குரூப் 4 வினாடி வினாவை முகப்புத் திரையில் சேர்க்கவும்: முழுத் திரையில் திறக்கும், தனிப் பயிற்சி ஆஃப்லைனிலும் இயங்கும்.'],
  'install.ios': ['On iPhone: tap Share, then “Add to Home Screen”.', 'iPhone-ல்: Share அழுத்தி “Add to Home Screen” தேர்வு செய்யவும்.'],
  'install.btn': ['Install', 'நிறுவு'],
  'install.later': ['Later', 'பிறகு'],

  'err.network': ['No connection. Check your internet and try again.', 'இணைப்பு இல்லை. இணையத்தைச் சரிபார்த்து மீண்டும் முயலவும்.'],
  'err.unknown': ['Something went wrong. Please try again.', 'ஏதோ தவறு நடந்தது. மீண்டும் முயலவும்.'],
  'err.not_authenticated': ['Please sign in again.', 'மீண்டும் உள்நுழையவும்.'],
  'err.not_onboarded': ['Finish setting up your profile first.', 'முதலில் சுயவிவரத்தை நிறைவு செய்யவும்.'],
  'err.insufficient_coins': ['Not enough coins.', 'நாணயங்கள் போதாது.'],
  'err.level_too_low': ['Unlocks at a higher level. Keep practising!', 'உயர் நிலையில் திறக்கும். பயிற்சியைத் தொடருங்கள்!'],
  'err.bad_stake': ['Choose one of the entry amounts.', 'நுழைவுத் தொகைகளில் ஒன்றைத் தேர்ந்தெடுக்கவும்.'],
  'err.stakes_frozen': ['Coin rooms are paused for this account while we review it.', 'மதிப்பாய்வு நடப்பதால் இக்கணக்குக்கு நாணய அறைகள் நிறுத்தப்பட்டுள்ளன.'],
  'err.in_match': ['Finish your current match first.', 'முதலில் நடப்புப் போட்டியை முடிக்கவும்.'],
  'err.room_not_found': ['No open room with that code.', 'அந்தக் குறியீட்டில் திறந்த அறை இல்லை.'],
  'err.room_in_match': ['That room is already playing. Wait for the next round.', 'அந்த அறையில் போட்டி நடக்கிறது. அடுத்த சுற்றுக்குக் காத்திருக்கவும்.'],
  'err.room_full': ['That room is full.', 'அறை நிரம்பிவிட்டது.'],
  'err.host_only': ['Only the host can do that.', 'நடத்துநர் மட்டுமே இதைச் செய்ய முடியும்.'],
  'err.not_all_ready': ['Everyone must tap Ready first.', 'அனைவரும் முதலில் "தயார்" அழுத்த வேண்டும்.'],
  'err.need_two_players': ['You need at least 2 players.', 'குறைந்தது 2 வீரர்கள் தேவை.'],
  'err.player_cannot_afford': ['{detail} does not have enough coins.', '{detail} அவர்களிடம் போதிய நாணயங்கள் இல்லை.'],
  'err.player_in_match': ['{detail} is in another match.', '{detail} வேறொரு போட்டியில் உள்ளார்.'],
  'err.daily_stake_cap': ['{detail} has reached today’s 5,000-coin entry limit.', '{detail} இன்றைய 5,000 நாணய நுழைவு வரம்பை எட்டியுள்ளார்.'],
  'err.not_enough_questions': ['Not enough fresh questions for this room. Try Mixed.', 'இந்த அறைக்குப் போதிய புதிய வினாக்கள் இல்லை. கலவையை முயலவும்.'],
  'err.question_closed': ['Too late: that question has closed.', 'தாமதம்: அந்த வினா முடிந்துவிட்டது.'],
  'err.too_late': ['Time was up.', 'நேரம் முடிந்துவிட்டது.'],
  'err.already_answered': ['Already answered.', 'ஏற்கெனவே விடையளித்தீர்கள்.'],
  'err.match_over': ['The match is over.', 'போட்டி முடிந்தது.'],
  'err.powerups_off': ['Power-ups are off in this room.', 'இந்த அறையில் உதவிகள் இல்லை.'],
  'err.powerup_used': ['Already used in this match.', 'இந்தப் போட்டியில் ஏற்கெனவே பயன்படுத்தப்பட்டது.'],
  'err.chat_muted': ['Your chat is paused for 24 hours after reports.', 'புகார்களால் உங்கள் அரட்டை 24 மணிநேரம் நிறுத்தப்பட்டுள்ளது.'],
  'err.rate_limited': ['Slow down a little.', 'சற்று மெதுவாக.'],
  'err.links_not_allowed': ['Links are not allowed in chat.', 'அரட்டையில் இணைப்புகளுக்கு அனுமதி இல்லை.'],
  'err.numbers_not_allowed': ['Phone numbers are not allowed in chat.', 'அரட்டையில் தொலைபேசி எண்களுக்கு அனுமதி இல்லை.'],
  'err.upi_not_allowed': ['UPI IDs and emails are not allowed in chat.', 'அரட்டையில் UPI / மின்னஞ்சல் முகவரிகளுக்கு அனுமதி இல்லை.'],
  'err.message_blocked': ['Please keep chat friendly.', 'அரட்டையை நட்பாக வைத்திருங்கள்.'],
  'err.message_too_long': ['Max 200 characters.', 'அதிகபட்சம் 200 எழுத்துகள்.'],
  'err.empty_message': ['Type a message first.', 'முதலில் செய்தியைத் தட்டச்சு செய்யவும்.'],
  'err.chat_closed': ['Text chat opens again after the match.', 'போட்டி முடிந்ததும் அரட்டை திறக்கும்.'],
  'err.not_friends': ['You can only message friends.', 'நண்பர்களுக்கு மட்டுமே செய்தி அனுப்பலாம்.'],
  'err.blocked': ['Not available.', 'கிடைக்கவில்லை.'],
  'err.username_taken': ['That username is taken.', 'அந்தப் பயனர் பெயர் ஏற்கெனவே உள்ளது.'],
  'err.bad_username': ['Use 3–20 characters: a–z, 0–9, _', '3–20 எழுத்துகள்: a–z, 0–9, _'],
  'err.bad_name': ['Enter your name.', 'உங்கள் பெயரை உள்ளிடவும்.'],
  'err.bad_district': ['Choose your district.', 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்.'],
  'err.bad_exam_year': ['Choose an exam year.', 'தேர்வு ஆண்டைத் தேர்ந்தெடுக்கவும்.'],
  'err.consent_required': ['Please confirm your age and accept the terms.', 'வயதை உறுதிசெய்து விதிமுறைகளை ஏற்கவும்.'],
  'err.daily_done': ['You have already played today’s challenge.', 'இன்றைய சவாலை ஏற்கெனவே விளையாடிவிட்டீர்கள்.'],
  'err.revision_empty': ['Your revision deck is empty. Great work!', 'மீள்பார்வைத் தொகுப்பு காலியாக உள்ளது. அருமை!'],
  'err.no_questions': ['No questions available yet for this choice.', 'இந்தத் தேர்வுக்கு இன்னும் வினாக்கள் இல்லை.'],
  'err.refill_not_needed': ['Top-up is only for balances under 50.', 'இருப்பு 50-க்குக் குறைவாக இருந்தால் மட்டுமே.'],
  'err.refill_cooldown': ['One top-up per 24 hours.', '24 மணிநேரத்துக்கு ஒரு முறை மட்டுமே.'],
  'err.shield_limit': ['You can hold up to 3 shields.', 'அதிகபட்சம் 3 கேடயங்கள்.'],
  'err.not_member': ['You are not in this room.', 'நீங்கள் இந்த அறையில் இல்லை.'],
  'err.not_in_match': ['You are not in this match.', 'நீங்கள் இந்தப் போட்டியில் இல்லை.'],
  'err.session_finished': ['This set is already finished.', 'இந்தப் பயிற்சி ஏற்கெனவே முடிந்தது.'],
  'err.user_not_found': ['Player not found.', 'வீரர் கிடைக்கவில்லை.'],
  'err.admin_only': ['Admins only.', 'நிர்வாகிகளுக்கு மட்டும்.'],
  'err.already_owned': ['You already have this.', 'இது ஏற்கெனவே உங்களிடம் உள்ளது.'],
  'err.not_owned': ['Buy it in the shop first.', 'முதலில் கடையில் வாங்கவும்.'],
  'err.not_found': ['Not found.', 'கிடைக்கவில்லை.'],

  'home.quick': ['Quick Match', 'விரைவுப் போட்டி'],
  'home.quickSub': ['Random opponent · 50 coins', 'புதிய எதிரி · 50 நாணயங்கள்'],
  'home.shop': ['Shop', 'கடை'],
  'home.leagueUp': ['Promoted to the {league} league!', '{league} லீக்குக்கு உயர்ந்தீர்கள்!'],
  'home.leagueDown': ['Moved to the {league} league. Climb back this week!', '{league} லீக்குக்கு இறங்கினீர்கள். இந்த வாரம் மீண்டும் ஏறுங்கள்!'],
  'home.leagueStay': ['You stayed in {league} (rank {rank}).', '{league} லீக்கில் தொடர்கிறீர்கள் (இடம் {rank}).'],
  'home.leagueCoins': ['+{coins} coins for your rank', 'உங்கள் இடத்துக்கு +{coins} நாணயங்கள்'],
  'home.chestOpen': ['Today’s reward collected', 'இன்றைய பரிசு பெறப்பட்டது'],
  'home.chestClosed': ['Finish a solo set to open today’s chest', 'இன்றைய பெட்டியைத் திறக்க ஒரு பயிற்சியை முடிக்கவும்'],

  'quick.title': ['Quick Match', 'விரைவுப் போட்டி'],
  'quick.searching': ['Finding an opponent near your level…', 'உங்கள் நிலைக்கு ஏற்ற எதிரியைத் தேடுகிறோம்…'],
  'quick.entry': ['Entry 50 coins · the winner gets 90', 'நுழைவு 50 நாணயங்கள் · வெற்றியாளருக்கு 90'],
  'quick.online': ['{n} searching now', 'இப்போது {n} பேர் தேடுகின்றனர்'],
  'quick.nobody': ['Nobody near your level is searching right now.', 'உங்கள் நிலையில் இப்போது யாரும் தேடவில்லை.'],
  'quick.bot': ['Play the practice bot (no stakes)', 'பயிற்சி பாட்டுடன் விளையாடு (நுழைவுத் தொகை இல்லை)'],
  'quick.keep': ['Keep searching', 'தொடர்ந்து தேடு'],

  'bot.name': ['Practice Bot', 'பயிற்சி பாட்'],
  'bot.title': ['Practice vs Bot', 'பாட்டுடன் பயிற்சி'],
  'bot.noStakes': ['Practice bot · no coins at stake', 'பயிற்சி பாட் · நுழைவுத் தொகை இல்லை'],
  'bot.youWin': ['You beat the bot!', 'பாட்டை வென்றீர்கள்!'],
  'bot.botWins': ['The bot won this time', 'இந்த முறை பாட் வென்றது'],
  'bot.draw': ['A draw!', 'சமநிலை!'],
  'bot.again': ['Play the bot again', 'மீண்டும் பாட்டுடன்'],

  'shop.title': ['Shop', 'கடை'],
  'shop.avatar': ['Avatars', 'அவதாரங்கள்'],
  'shop.frame': ['Frames', 'சட்டகங்கள்'],
  'shop.emoji_pack': ['Emoji packs', 'எமோஜி தொகுப்புகள்'],
  'shop.theme': ['Room themes', 'அறைத் தோற்றங்கள்'],
  'shop.buy': ['Buy', 'வாங்கு'],
  'shop.equip': ['Use', 'பயன்படுத்து'],
  'shop.equipped': ['In use', 'பயன்பாட்டில்'],
  'shop.remove': ['Take off', 'நீக்கு'],
  'shop.owned': ['Yours', 'உங்களுடையது'],
  'shop.locked': ['Level {n}', 'நிலை {n}'],
  'shop.note': ['Paid with game coins only. Nothing here costs real money.', 'விளையாட்டு நாணயங்களால் மட்டும். இங்கு எதற்கும் உண்மைப் பணம் இல்லை.'],
  'shop.bought': ['Bought: {name}', 'வாங்கப்பட்டது: {name}'],
  'shop.packHint': ['Adds these reactions in rooms', 'அறைகளில் இந்த எதிர்வினைகளைச் சேர்க்கும்'],
  'shop.themeHint': ['Rooms you host get this background', 'நீங்கள் நடத்தும் அறைகளுக்கு இந்தப் பின்னணி'],
  'shop.confirm': ['Buy {name} for {price} coins?', '{name}-ஐ {price} நாணயங்களுக்கு வாங்கவா?'],

  'lb.league': ['League', 'லீக்'],
  'league.title': ['{league} league', '{league} லீக்'],
  'league.join': ['Earn XP this week to join a league group of up to 30 players.', 'இந்த வாரம் XP சேர்த்து 30 பேர் வரையிலான லீக் குழுவில் சேருங்கள்.'],
  'league.ends': ['Ends in {d}d {h}h', '{d} நாள் {h} மணியில் முடியும்'],
  'league.rules': ['Top {up} move up, bottom {down} move down every Monday.', 'ஒவ்வொரு திங்கள்: முதல் {up} பேர் மேலே, கடைசி {down} பேர் கீழே.'],
  'league.rewards': ['Top 3 win {a} / {b} / {c} coins in groups of {min}+.', '{min}+ பேர் குழுவில் முதல் மூவருக்கு {a} / {b} / {c} நாணயங்கள்.'],
  'league.zoneUp': ['Promotion zone', 'உயர்வு மண்டலம்'],
  'league.zoneDown': ['Relegation zone', 'இறக்க மண்டலம்'],

  'push.toggle': ['Notifications (room invites, streak reminders)', 'அறிவிப்புகள் (அறை அழைப்பு, தொடர் நினைவூட்டல்)'],
  'push.denied': ['Notifications are blocked in your browser settings.', 'உலாவி அமைப்புகளில் அறிவிப்புகள் தடுக்கப்பட்டுள்ளன.'],
  'push.install': ['On iPhone, install the app first (Share → Add to Home Screen).', 'iPhone-ல் முதலில் செயலியை நிறுவவும் (Share → Add to Home Screen).'],
  'push.unsupported': ['This browser does not support notifications.', 'இந்த உலாவியில் அறிவிப்புகள் இல்லை.'],
  'push.on': ['Notifications on', 'அறிவிப்புகள் இயக்கப்பட்டன'],

  'profile.analytics': ['Share anonymous usage data', 'அநாமதேயப் பயன்பாட்டுத் தரவைப் பகிர்'],
  'profile.shop': ['Shop', 'கடை'],
  'onb.analytics': ['Help improve the app by sharing anonymous usage data (optional)', 'அநாமதேயப் பயன்பாட்டுத் தரவைப் பகிர்ந்து செயலியை மேம்படுத்த உதவுங்கள் (விருப்பம்)'],
  'app.crashed': ['Something went wrong. We have been told about it.', 'ஏதோ தவறு நடந்தது. எங்களுக்குத் தெரிவிக்கப்பட்டது.'],
  'app.reload': ['Reload', 'மீண்டும் ஏற்று'],
  'levelup.title': ['Level {n}!', 'நிலை {n}!'],

  'reason.shop': ['Shop', 'கடை'],
  'reason.league': ['League reward', 'லீக் பரிசு'],
} as const satisfies Record<string, readonly [string, string]>;

export type StringKey = keyof typeof strings;
