// Builds supabase/seed.sql and src/demo/samplePack.json from
// content/questions.sample.json. In the source file the first option is the
// correct one; here options are shuffled (same order for both languages) with
// a fixed seed, so the output is stable between runs.
//
//   npm run seed
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const { questions } = JSON.parse(readFileSync(join(root, 'content', 'questions.sample.json'), 'utf8'));

function mulberry32(seed) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const sqlText = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const sqlArray = (a) => (a == null ? 'null' : `array[${a.map(sqlText).join(', ')}]`);

const rows = [];
const pack = [];
questions.forEach((q, i) => {
  for (const lang of ['ta', 'en']) {
    if (q[lang] && q[lang].o.length !== 4) throw new Error(`Question ${i + 1}: ${lang} needs 4 options`);
  }
  if (!q.ta && !q.en) throw new Error(`Question ${i + 1}: no text`);
  const rand = mulberry32(i + 1);
  const order = [0, 1, 2, 3];
  for (let k = 3; k > 0; k--) {
    const j = Math.floor(rand() * (k + 1));
    [order[k], order[j]] = [order[j], order[k]];
  }
  const answer = order.indexOf(0);
  const shuffle = (opts) => (opts ? order.map((k) => opts[k]) : null);
  const item = {
    unit: q.unit,
    subtopic: q.subtopic,
    difficulty: q.difficulty,
    text_ta: q.ta?.q ?? null,
    text_en: q.en?.q ?? null,
    options_ta: shuffle(q.ta?.o),
    options_en: shuffle(q.en?.o),
    answer,
    explanation_ta: q.ta?.e ?? null,
    explanation_en: q.en?.e ?? null,
    book_ref: q.book_ref ?? null,
  };
  pack.push({ id: -(i + 1), ...item });
  rows.push(
    `(${sqlText(item.unit)}, ${sqlText(item.subtopic)}, ${item.difficulty}, ${sqlText(item.text_ta)}, ${sqlText(item.text_en)}, ` +
      `${sqlArray(item.options_ta)}, ${sqlArray(item.options_en)}, ${answer}, ${sqlText(item.explanation_ta)}, ` +
      `${sqlText(item.explanation_en)}, 'sample-ai-draft', 'live')`,
  );
});

const sql = `-- Generated by scripts/build-seed.mjs from content/questions.sample.json. Do not edit by hand.
-- ${rows.length} AI-drafted sample questions, live for development and beta testing.
-- Before public launch, send them through the two-reviewer queue:
--   update public.questions set status = 'review', reviewed_by = '{}' where source = 'sample-ai-draft';
insert into public.questions
  (unit, subtopic, difficulty, text_ta, text_en, options_ta, options_en, answer, explanation_ta, explanation_en, source, status)
values
${rows.join(',\n')};
`;

writeFileSync(join(root, 'supabase', 'seed.sql'), sql);
mkdirSync(join(root, 'src', 'demo'), { recursive: true });
writeFileSync(join(root, 'src', 'demo', 'samplePack.json'), JSON.stringify(pack));
const byUnit = pack.reduce((m, q) => ((m[q.unit] = (m[q.unit] ?? 0) + 1), m), {});
console.log(`Wrote ${rows.length} questions:`, byUnit);
